#!/usr/bin/env bash
# Interactive setup for gh-activity-mirror.
# Asks for usernames, creates the mirror repo, resolves the noreply email,
# and writes config.env.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.env"
EXAMPLE_FILE="${SCRIPT_DIR}/config.env.example"

say()  { printf "\033[1;34m→\033[0m %s\n" "$*"; }
ok()   { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m!\033[0m %s\n" "$*" >&2; }
die()  { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; exit 1; }

ask() {
  # ask VAR "Prompt text" ["default"]
  local __var="$1" __prompt="$2" __default="${3-}" __answer
  if [[ -n "$__default" ]]; then
    read -r -p "$__prompt [$__default]: " __answer
    __answer="${__answer:-$__default}"
  else
    read -r -p "$__prompt: " __answer
  fi
  printf -v "$__var" '%s' "$__answer"
}

confirm() {
  local prompt="$1" ans
  read -r -p "$prompt [y/N]: " ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

# --- prerequisites ---------------------------------------------------------

for cmd in gh jq git; do
  command -v "$cmd" >/dev/null || die "$cmd is not installed. Install it and re-run."
done

if [[ -f "$CONFIG_FILE" ]]; then
  warn "$CONFIG_FILE already exists."
  if ! confirm "Overwrite it?"; then
    echo "Aborted. Existing config left untouched."
    exit 0
  fi
fi

# --- accounts --------------------------------------------------------------

say "Which GitHub account's activity do you want to MIRROR FROM (the source — usually your work account)?"
ask WORK_USER "Source username"

say "Which GitHub account should RECEIVE the mirrored commits (the target — usually your personal account)?"
ask PERSONAL_USER "Target username"

[[ "$WORK_USER" != "$PERSONAL_USER" ]] || die "Source and target must be different accounts."

# Confirm both are signed into gh.
say "Checking gh auth for both accounts…"
for u in "$WORK_USER" "$PERSONAL_USER"; do
  if gh auth status 2>&1 | grep -q "account $u "; then
    ok "signed in as $u"
  else
    warn "Not signed in as $u."
    echo "  Run: gh auth login   (and add $u), then re-run ./setup.sh"
    exit 1
  fi
done

# --- mirror repo -----------------------------------------------------------

default_repo_name="activity-mirror"
ask MIRROR_NAME "Name for the private mirror repo on $PERSONAL_USER" "$default_repo_name"
MIRROR_REPO="${PERSONAL_USER}/${MIRROR_NAME}"

say "Switching gh to $PERSONAL_USER…"
gh auth switch --user "$PERSONAL_USER" >/dev/null

if gh repo view "$MIRROR_REPO" >/dev/null 2>&1; then
  ok "$MIRROR_REPO already exists — will reuse it."
else
  say "Creating private repo $MIRROR_REPO…"
  gh repo create "$MIRROR_REPO" --private --clone=false >/dev/null
  ok "created $MIRROR_REPO"
fi

# --- commit identity -------------------------------------------------------

say "Fetching the noreply email for $PERSONAL_USER…"
DEFAULT_EMAIL=$(gh api user --jq '"\(.id)+\(.login)@users.noreply.github.com"' 2>/dev/null || true)
if [[ -z "$DEFAULT_EMAIL" ]]; then
  warn "Couldn't fetch noreply email automatically."
  ask PERSONAL_EMAIL "Email verified on $PERSONAL_USER"
else
  ask PERSONAL_EMAIL "Email verified on $PERSONAL_USER" "$DEFAULT_EMAIL"
fi
ask PERSONAL_NAME "Commit author display name" "$PERSONAL_USER"

# --- write config ----------------------------------------------------------

umask 077
cat > "$CONFIG_FILE" <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit freely — see config.env.example for documentation of each field.

WORK_USER="$WORK_USER"
PERSONAL_USER="$PERSONAL_USER"
MIRROR_REPO="$MIRROR_REPO"
PERSONAL_EMAIL="$PERSONAL_EMAIL"
PERSONAL_NAME="$PERSONAL_NAME"
EOF

ok "Wrote $CONFIG_FILE"

# --- reminders -------------------------------------------------------------

cat <<EOF

Almost done. One thing setup can't do for you:

  → Enable "Include private contributions on my profile"
    https://github.com/settings/profile
    (otherwise commits in the private mirror repo won't show on the graph)

Then:

  ./sync.sh --dry-run   # preview
  ./sync.sh             # actually mirror

EOF
